project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Xavier Martinez: Future Consequences Graphs"
  navbar:
    right:
      - icon: github
        href: https://github.com/CrumpLab/quartoCourseBlog
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: yeti
    css: styles.css

editor: visual

